version: 0
os: linux
files:
  - source: /
    destination: /home/ssm-user/education-backend
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 1500
      runas: ssm-user
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 500
      runas: ssm-user
  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 1500
      runas: ssm-user
