export const jwtConstants = {
  secret: process.env.JWT_SECRET || 'secret',
};

export const RESOURCES = [
  {
    "id": "1",
    "Content title": "Framework for teaching news literacy",
    "Journalist(s) or SME": "",
    "Link to content": "https://newslit.org/wp-content/uploads/2022/02/1_13_22_NLP_Final_Framework-2.pdf",
    "Link to description": "https://newslit.org/educators/resources/framework-for-teaching-news-literacy/",
    "Resource type": "📑 Teaching tips & strategies",
    "NLNO top navigation": "Professional learning,Resource library",
    "Format(s)": "Framework",
    "Classroom needs": "",
    "Subject areas": "",
    "NLP standards": "",
    "News literacy topics": "",
    "Content warnings": "",
    "Grade level": "6-8,9-12",
    "⌛ Estimated time to complete": "N/A",
    "Evaluation preference": "No assessments",
    "Assessment types": "N/A",
    "Prerequisites": "dsdds, sdssd"
 },
  {
    "id": "2",
    "Content title": "How to teach news literacy in polarizing times",
    "Journalist(s) or SME": "",
    "Link to content": "http://newslit.org/wp-content/uploads/2021/07/PolarizingTimes_FINAL.pdf",
    "Link to description": "https://newslit.org/educators/resources/how-to-teach-news-literacy-in-polarizing-times/",
    "Resource type": "📑 Teaching tips & strategies",
    "NLNO top navigation": "Professional learning,Resource library",
    "Format(s)": "Infographic",
    "Grade level": "3-4",
    "Classroom needs": "",
    "Subject areas": "✏️ ELA,💻 Library/media studies,🪶 Social studies,📰 Journalism,🧪 STEM,🎨 Arts",
    "NLP standards": "S1: ℹ️ Students distinguish news from other types of information and can recognize both traditional and non-traditional ads.,S2: 🪶 Students acknowledge the importance of the First Amendment in American democracy and a free press to an informed public.,S3:  📰 Students understand the standards of quality journalism and can use them to identify credible information and sources.,\"S4: 🚨Students demonstrate increased critical habits of mind, including effective verification skills and the ability to detect misinformation and faulty evidence.\",S5: 🏛️ Students express a sense of responsibility for the information they share and feel more empowered to be civically engaged.",
    "News literacy topics": "Standards of quality journalism,Bias",
    "Content warnings": "",
    "⌛ Estimated time to complete": "N/A",
    "Evaluation preference": "No assessments",
    "Assessment types": "N/A",
    "Prerequisites": "Misinformation"
 },
  {
    "id": "3",
    "Content title": "Teaching News Literacy: Where do I start? (Fall webinar series 2021)",
    "Journalist(s) or SME": "John Silva",
    "Link to content": "https://www.youtube.com/watch?v=jt1oreWj7b4&t=130s",
    "Link to description": "https://newslit.org/updates/kick-off-the-school-year-with-nlps-fall-news-literacy-webinar-series/",
    "Resource type": "📑 Teaching tips & strategies",
    "NLNO top navigation": "Professional learning,Resource library",
    "Format(s)": "Video",
    "Grade level": "6-8,9-12",
    "Classroom needs": "Contains audio/video",
    "Subject areas": "✏️ ELA,💻 Library/media studies,🪶 Social studies,📰 Journalism,🧪 STEM",
    "NLP standards": "S1: ℹ️ Students distinguish news from other types of information and can recognize both traditional and non-traditional ads.,S2: 🪶 Students acknowledge the importance of the First Amendment in American democracy and a free press to an informed public.,S3:  📰 Students understand the standards of quality journalism and can use them to identify credible information and sources.,\"S4: 🚨Students demonstrate increased critical habits of mind, including effective verification skills and the ability to detect misinformation and faulty evidence.\",S5: 🏛️ Students express a sense of responsibility for the information they share and feel more empowered to be civically engaged.",
    "News literacy topics": "Primary purpose,Opinion,News judgment,Standards of quality journalism,Evaluating evidence,Misinformation,Fact-checking and verification",
    "Content warnings": "",
    "⌛ Estimated time to complete": "30 - 60 min",
    "Evaluation preference": "No assessments",
    "Assessment types": "N/A",
    "Prerequisites": "Misinformation"
 },
  {
    "id": "4",
    "Content title": "Understanding Bias (Fall webinar series 2021)",
    "Journalist(s) or SME": "Peter Adams",
    "Link to content": "https://www.youtube.com/watch?v=YcJFnudLr3c",
    "Link to description": "https://newslit.org/updates/kick-off-the-school-year-with-nlps-fall-news-literacy-webinar-series/",
    "Resource type": "📑 Teaching tips & strategies",
    "NLNO top navigation": "Professional learning,Resource library",
    "Format(s)": "Video",
    "Grade level": "6-8,9-12",
    "Classroom needs": "Contains audio/video",
    "Subject areas": "✏️ ELA,💻 Library/media studies,🪶 Social studies,📰 Journalism",
    "NLP standards": "S3:  📰 Students understand the standards of quality journalism and can use them to identify credible information and sources.",
    "News literacy topics": "Bias,Standards of quality journalism",
    "Content warnings": "",
    "⌛ Estimated time to complete": "30 - 60 min",
    "Evaluation preference": "No assessments",
    "Assessment types": "N/A",
    "Prerequisites": "Misinformation"
 },
  {
    "id": "5",
    "Content title": "Exploring the misinformation landscape (Fall webinar series 2021)",
    "Journalist(s) or SME": "John Silva",
    "Link to content": "https://www.youtube.com/watch?v=Ah4UOddX_Ug",
    "Link to description": "https://newslit.org/updates/kick-off-the-school-year-with-nlps-fall-news-literacy-webinar-series/",
    "Resource type": "📑 Teaching tips & strategies",
    "NLNO top navigation": "Professional learning,Resource library",
    "Format(s)": "Video",
    "Grade level": "6-8,9-12",
    "Classroom needs": "Contains audio/video",
    "Subject areas": "✏️ ELA,💻 Library/media studies,🪶 Social studies,📰 Journalism,🧪 STEM",
    "NLP standards": "\"S4: 🚨Students demonstrate increased critical habits of mind, including effective verification skills and the ability to detect misinformation and faulty evidence.\"",
    "News literacy topics": "Misinformation,Fact-checking and verification,Algorithms and personalization,Evaluating evidence,Conspiratorial thinking,Science and data reporting",
    "Content warnings": "",
    "⌛ Estimated time to complete": "30 - 60 min",
    "Evaluation preference": "No assessments",
    "Assessment types": "N/A",
    "Prerequisites": "Misinformation"
 },
  {
    "id": "6",
    "Content title": "NewsLit Teaching Strategies: Checkology®'s \"Power in Art\" lesson on editorial cartooning",
    "Journalist(s) or SME": "Peter Adams,Adriana Chavira,Molly Roquet",
    "Link to content": "https://youtu.be/yw2rgTp_93k",
    "Link to description": "https://newslit.org/updates/nlp-webinar-power-in-art-exploring-a-new-checkology-lesson/?utm_campaign=pia-event-apr11&utm_source=power-in-art&utm_medium=email&emci=07057546-51b7-ec11-997e-281878b83d8a&emdi=65c3957a-c5b9-ec11-997e-281878b83d8a&ceid=9662977",
    "Resource type": "📑 Teaching tips & strategies",
    "NLNO top navigation": "Professional learning,Resource library",
    "Format(s)": "Video",
    "Grade level": "6-8,9-12",
    "Classroom needs": "Contains audio/video,Keyboard navigable",
    "Subject areas": "✏️ ELA,💻 Library/media studies,🪶 Social studies,📰 Journalism,🎨 Arts",
    "NLP standards": "S2: 🪶 Students acknowledge the importance of the First Amendment in American democracy and a free press to an informed public.",
    "News literacy topics": "Propaganda,Primary purpose,Investigative journalism / watchdog role,A free press,Standards of quality journalism,Evaluating evidence",
    "Content warnings": "",
    "⌛ Estimated time to complete": "30 - 60 min",
    "Evaluation preference": "No assessments",
    "Assessment types": "N/A",
     "Prerequisites": "Misinformation"
 },
  {
    "id": "7",
    "Content title": "Local News: Teaching with Storm Lake",
    "Journalist(s) or SME": "Jill Hoffmockel,Pam Brunskill",
    "Link to content": "https://www.youtube.com/watch?v=995Qpp_dZE8",
    "Link to description": "https://newslit.org/updates/webinar-local-news-teaching-with-storm-lake/",
    "Resource type": "📑 Teaching tips & strategies",
    "NLNO top navigation": "Professional learning,Resource library",
    "Format(s)": "Video",
    "Grade level": "6-8,9-12",
    "Classroom needs": "Contains audio/video,Keyboard navigable",
    "Subject areas": "✏️ ELA,💻 Library/media studies,🪶 Social studies,📰 Journalism",
    "NLP standards": "S2: 🪶 Students acknowledge the importance of the First Amendment in American democracy and a free press to an informed public.",
    "News literacy topics": "Investigative journalism / watchdog role,A free press",
    "Content warnings": "",
    "⌛ Estimated time to complete": "> 60 min",
    "Evaluation preference": "No assessments",
    "Assessment types": "N/A",
    "Prerequisites": "Misinformation"
 },
  {
    "id": "8",
    "Content title": "What is News? Poster",
    "Journalist(s) or SME": "",
    "Link to content": "http://newslit.org/wp-content/uploads/2021/01/WhatIsNews-Poster.pdf",
    "Link to description": "https://newslit.org/educators/resources/what-is-news/",
    "Resource type": "📊 Explainer",
    "NLNO top navigation": "Resource library",
    "Format(s)": "Poster",
    "Grade level": "6-8,9-12",
    "Classroom needs": "No tech required",
    "Subject areas": "✏️ ELA,💻 Library/media studies,🪶 Social studies,📰 Journalism",
    "NLP standards": "S1: ℹ️ Students distinguish news from other types of information and can recognize both traditional and non-traditional ads.",
    "News literacy topics": "News judgment",
    "Content warnings": "",
    "⌛ Estimated time to complete": "N/A",
    "Evaluation preference": "No assessments",
    "Assessment types": "N/A",
    "Prerequisites": "Misinformation"
 },
  {
    "id": "9",
    "Content title": "In brief: Misinformation",
    "Journalist(s) or SME": "",
    "Link to content": "https://newslit.org/wp-content/uploads/2021/12/Misinfo_infographic_FINAL.pdf",
    "Link to description": "https://newslit.org/educators/resources/in-brief-misinformation/",
    "Resource type": "📊 Explainer",
    "NLNO top navigation": "Resource library",
    "Format(s)": "Infographic",
    "Grade level": "6-8,9-12",
    "Classroom needs": "No tech required",
    "Subject areas": "✏️ ELA,💻 Library/media studies,🪶 Social studies,📰 Journalism,🧪 STEM",
    "NLP standards": "\"S4: 🚨Students demonstrate increased critical habits of mind, including effective verification skills and the ability to detect misinformation and faulty evidence.\"",
    "News literacy topics": "Misinformation,Conspiratorial thinking,Digital citizenship",
    "Content warnings": "",
    "⌛ Estimated time to complete": "N/A",
    "Evaluation preference": "No assessments",
    "Assessment types": "N/A",
    "Prerequisites": "Misinformation"
 },
  {
    "id": "10",
    "Content title": "Is it legit? Five steps for vetting a news source",
    "Journalist(s) or SME": "SmartNews",
    "Link to content": "https://newslit.org/wp-content/uploads/2021/11/IsItLegit_infographic.pdf",
    "Link to description": "https://newslit.org/educators/resources/is-it-legit/",
    "Resource type": "📊 Explainer",
    "NLNO top navigation": "Resource library",
    "Format(s)": "Infographic",
    "Grade level": "6-8,9-12",
    "Classroom needs": "No tech required",
    "Subject areas": "✏️ ELA,💻 Library/media studies,🪶 Social studies,📰 Journalism,🧪 STEM",
    "NLP standards": "S3:  📰 Students understand the standards of quality journalism and can use them to identify credible information and sources.,\"S4: 🚨Students demonstrate increased critical habits of mind, including effective verification skills and the ability to detect misinformation and faulty evidence.\"",
    "News literacy topics": "Standards of quality journalism,Bias,Fact-checking and verification,Opinion",
    "Content warnings": "",
    "⌛ Estimated time to complete": "N/A",
    "Evaluation preference": "No assessments",
    "Assessment types": "N/A",
    "Prerequisites": "Misinformation"
 },
  {
    "id": "11",
    "Content title": "Eight tips to Google like a pro",
    "Journalist(s) or SME": "Cindy Otis",
    "Link to content": "https://newslit.org/wp-content/uploads/2021/06/Eight-Tips-to-Google-Like-a-Pro_2021_FINALVERSION.pdf",
    "Link to description": "https://newslit.org/educators/resources/eight-tips-to-google-like-a-pro/",
    "Resource type": "📊 Explainer",
    "NLNO top navigation": "Resource library",
    "Format(s)": "Infographic",
    "Grade level": "6-8,9-12",
    "Classroom needs": "No tech required",
    "Subject areas": "✏️ ELA,💻 Library/media studies,🪶 Social studies,📰 Journalism,🧪 STEM",
    "NLP standards": "\"S4: 🚨Students demonstrate increased critical habits of mind, including effective verification skills and the ability to detect misinformation and faulty evidence.\"",
    "News literacy topics": "Fact-checking and verification,Misinformation,Conspiratorial thinking,Digital citizenship",
    "Content warnings": "",
    "⌛ Estimated time to complete": "N/A",
    "Evaluation preference": "No assessments",
    "Assessment types": "N/A",
    "Prerequisites": "Misinformation"
 },
  {
    "id": "12",
    "Content title": "Conspiratorial Thinking (poster)",
    "Journalist(s) or SME": "",
    "Link to content": "https://newslit.org/wp-content/uploads/2021/01/ConspiratorialThinking-Poster.pdf",
    "Link to description": "https://newslit.org/educators/resources/conspiratorial-thinking/",
    "Resource type": "📊 Explainer",
    "NLNO top navigation": "Resource library",
    "Format(s)": "Poster",
    "Grade level": "6-8,9-12",
    "Classroom needs": "No tech required",
    "Subject areas": "✏️ ELA,💻 Library/media studies,🪶 Social studies,📰 Journalism,🧪 STEM",
    "NLP standards": "\"S4: 🚨Students demonstrate increased critical habits of mind, including effective verification skills and the ability to detect misinformation and faulty evidence.\"",
    "News literacy topics": "Conspiratorial thinking",
    "Content warnings": "",
    "⌛ Estimated time to complete": "N/A",
    "Evaluation preference": "No assessments",
    "Assessment types": "N/A",
    "Prerequisites": "Misinformation"
 },
  {
    "id": "13",
    "Content title": "The First Amendment (poster)",
    "Journalist(s) or SME": "",
    "Link to content": "http://newslit.org/wp-content/uploads/2021/01/FirstAmendment-Poster.pdf",
    "Link to description": "https://newslit.org/educators/resources/the-first-amendment/",
    "Resource type": "📊 Explainer",
    "NLNO top navigation": "Resource library",
    "Format(s)": "Poster",
    "Grade level": "6-8,9-12",
    "Classroom needs": "No tech required",
    "Subject areas": "🪶 Social studies,💻 Library/media studies,📰 Journalism",
    "NLP standards": "S2: 🪶 Students acknowledge the importance of the First Amendment in American democracy and a free press to an informed public.",
    "News literacy topics": "The First Amendment",
    "Content warnings": "",
    "⌛ Estimated time to complete": "N/A",
    "Evaluation preference": "No assessments",
    "Assessment types": "N/A",
    "Prerequisites": "Misinformation"
 }
]