export const CUSTOM_FIELD_GROUP_ID = 348;
export const CREATION_DATE_FIELD_ID = 1671;
export const CUSTOM_FIELD_LAST_LOGIN_ID = 1908;
export const CUSTOM_FIELD_CONTACT_ID = 1670;
export const VAN_ID_KEY_NAME = 'everyActionVanId';

export const fieldDescriptions: { [fieldId: string]: string } = {
  "fld0e4a8rxJH0vuuN" : "Resource ID",
  "fldVKCCmxAU8ivmgS" : "Content title",
  "fldlOUT8NOFWR7eu4" : "Link to content",
  "fldNKdM1u2xGaCisy" : "Link to description",
  "fldYoPtenYkBNmtP3" : `"About" text`,
  "fldcisSrNS4KSyMqR" : "Link to transcript",
  "fldntF05KZMm0UTY5" : "Journalist(s) or SME",
  "fldy7rmsL2CDJnAVP" : "Journalist or SME organization(s)",
  "fld9onqOwHVbqPLfQ" : "Resource type (USE THIS)",
  "fld24UF2TsoWksXwB" : "Resource type (recent old)",
  "fld2MMMqUu3Wbxnga" : "Only on Checkology",
  "fldHYoFtqOI9smFxf" : "Featured in the Sift",
  "fldyEwngEmRoBrzGE" : "Format(s)",
  "fldszXbyHzZLewF5b" : "Grade level/band",
  "fldQxYib3D0CD1g7A" : "Classroom needs",
  "fldZCF1mhfTd0YWUe" : "Subject areas",
  "fldIwVRntZnsIBVxO" : "NLP standards",
  "fldkwKFB80aSu5S2K" : "News literacy topics",
  "fld9YDWlGsSrNjfL5" : "Content warnings",
  "fldm4RBxT9KCEERAR" : "Content warning to be added to content",
  "fldYYPPNxtMFMl1zo" : "Estimated time to complete",
  "fldy33pPzmKoCSYWK" : "Evaluation preference",
  "fldXwEIAagskYtoG1" : "Assessment types",
  "fldLHarViU5fAPJXF" : "Prerequisites/related",
  "flda0vQn27WQfwW2H" : "Creation date",
  "fldU0MIlOu2YINjHW" : "Date of last review",
  "fldA6oBkZ9Skic5Af" : "Date of last modification",
  "fldYjZ1bGZBVI6tNW" : "Word wall terms",
  "fldZTkFvGfsYHrJqm" : "Word wall terms to link",
  "fld4PHHkb7iY1wP6x" : "Media outlets featured",
  "fldzvRYDufuXeQCpy" : "Media outlets mentioned",
  "fldGO6oStQQuN0umW" : "Checkology overview page complete",
  "fld0a8gyulKMP9PX9" : "Learning objectives and essential questions",
  "fldkkXlQiVmOwvekQ" : "Audit status",
  "fldhXOrWd97YLbmNq" : "Link to audit",
  "fldz0us3vvhG8Mnis" : "Status",
  "fldKAkh4bo9K7feAi" : "Image status",
  "fldFdhvuA0MOTfga7" : "Image group",
  "fldWNUc6cm1DqIFjG" : "About text characters",
  "fldYhskMbnN4vdwPM" : "Resource type (OLD)",
  "fld7NE4f3jG1ueUcG" : "Links to standards alignments",
  "fldqVkHQ1dK407b8P" : "Average completion times",
  "fldamyBfrmlxSpR5p" : "Searchable tags",
  "fldVOugrqM2a5yUJ7" : "User feedback",
  "fldMNk02KM1OqRSq9" : "Reporters and SMEs",
  "flduk02p4dO5qbEIx" : "NLNO top navigation",
  "fld5zk4552Jh9QJ97" : "Why should it go dormant?",
  "fldJT135pdm9vXA9Z" : "Checkology points",
  "fldzBAQgpBJWQwJc3" : "Name of link",
  "fldZCEM9wKS6XE3rb" : "Link to content (2)",
  "fldr4Ujm5ijg47imV" : "Name of link (2)",
  "fldLkysrRPKbXuLJW" : "Standards alignments",
  "fldZQUS9x1pZBSYot" : "Primary image",
  "fld6YyNy29lk0z8nO" : "Primary image alt text",
  "fldeA4ZmCCuWrlMwX" : "Thumbnail image",
  "fldkyNNsmJg7MRCym" : "Thumbnail image alt text",
  "fld92LE4dxStPqXs6" : "Social image",
  "fldgIQhKjcgB071qW" : "Social image alt text",
  "fldnm7UZaPO6YtVMm" : "NewsLitNation exclusive",
  "fld2sDVnNuz3FJtCU" : "Design Notes",
  "fldpmmLc5G78WS04r" : "Primary image URL",
  "fldCa26yx6aN20Rq1" : "Thumbnail image URL",
  "fldjSKk3PtEUDP74q" : "URL slug (nlpeducation.org/resources/_____)"

  ///Below is the arslan airtable field description
  // "fldc2H1I2fR2epttQ": "Content title",
  // "fldp5HrDW01BJvIys": "Status",
  // "fldFh8TdnGfxJYq7Z": "NewsLitNation exclusive",
  // "fldydymQmqfb7HdVi": "Image group",
  // "fldjWTjQgE1761RZ4": "Image status",
  // "fld7Asnj9gVvJow3p": "About text",
  // "fldzH355wem3gvLtH": "Link to transcript",
  // "fldhvzjKHo8HNOWle": "Journalist(s) or SME",
  // "fld7JSomwUvdSNQhG": "Journalist or SME organization(s)",
  // "fldY46Ow5uDW3Pps8": "Resource type (USE THIS)",
  // "fldgDOz9KEdlhx2zD": "Resource type (recent old)",
  // "fldYr4Jy33afhKTDQ": "Resource type (OLD)",
  // "fldEfvrENfLm25S0v": "Only on Checkology",
  // "fldRY8vl0qJoHxdzf": "Featured in the Sift",
  // "fld6E6qo7GZdfUivK": "Format(s)",
  // "fldnjUbISnGXnW7bH": "Name of link",
  // "fldiHSGvuHL7T4cyo": "Link to content",
  // "fldbazwMCSp4Wkzck": "Link to description",
  // "fldLj4JKv0Y4ZHQCc": "Grade level/band",
  // "fldan0DTGvDYxqyn0": "Classroom needs",
  // "fldVkNrDx2oFY3yHE": "Subject areas",
  // "flduUiETVRowzuXRC": "NLP standards",
  // "fldfib7Z6AbYPzZVm": "News literacy topics",
  // "fldqMpIWZbKPt1r5K": "Content warnings",
  // "fldSW0vx4jJPIQ9TZ": "Content warning to be added to content",
  // "fld1kWksYAS780cmS": "Estimated time to complete",
  // "fldiinCAfSTM2EQfI": "Links to standards alignments",
  // "fldV4U0mo8X7K5Qb1": "Average completion times",
  // "fldRW7FZAis07owoy": "Evaluation preference",
  // "fldYjp4TJfsvWdwQT": "Assessment types",
  // "fld1xTnOCK96cAyuQ": "Prerequisites/related",
  // "fldB5xCe1m0ZStAYn": "Searchable tags",
  // "fldpL1SOMG4aqRCgr": "Creation date",
  // "fldXOdq6SxGFKNhvc": "Date of last review",
  // "fldaVyIQftpTd1ETG": "Date of last modification",
  // "fldEf0ryFsxsorsyS": "User feedback",
  // "fldej912m9dZXWSbB": "Word wall terms",
  // "fldP7FENBIw8q9hf1": "Word wall terms to link",
  // "fldlC8TG35oDjOUBy": "Media outlets featured",
  // "fld6JGcTaV6KjGpfg": "Media outlets mentioned",
  // "fldk0Tb1w11BB8tb0": "Reporters and SMEs",
  // "fldHmH0rrzjY5uav6": "Checkology overview page complete",
  // "fld575A27H43puioA": "Learning objectives and essential questions",
  // "fldbHra8LvCUeQ1sP": "NLNO top navigation",
  // "fld9Hq3R7oEhGYcUq": "Field 35",
  // "fldXlZOOdeZ9ohFAQ": "Why should it go dormant?",
  // "fldRK2Cx0E46QP6Is": "Audit status",
  // "fldhk2jBCzoCLjlvw": "Link to audit",
  // "fldpD1WvPFLHVxRs7": "Checkology points",
  // "fld2csHQtBnP780PP": "Link to content (2)",
  // "fldcifY3oCktcHJad": "Name of link (2)",
  // "fldYEUuvtphVjOFtV": "Field 49",
  // "fld6Up2yd0WeFmlWe": "Standards alignments",
  // "fldoTXibWopCbnFUH": "Primary image",
  // "fldWYIQrR6BfbpC0Q": "Primary image alt text",
  // "fldNpqcOpFFNX84tP": "Thumbnail image",
  // "fldfg84Mj6LWErhUv": "Thumbnail image alt text",
  // "fldPDx81qA8pVPiim": "Social image",
  // "fldrRMJKampqxr02L": "Social image alt text"
};
