export const CUSTOM_FIELD_GROUP_ID = 348;
export const CREATION_DATE_FIELD_ID = 1671;
export const CUSTOM_FIELD_LAST_LOGIN_ID = 1908;
export const CUSTOM_FIELD_CONTACT_ID = 1670;
export const VAN_ID_KEY_NAME = 'everyActionVanId';

export const fieldDescriptions: { [fieldId: string]: string } = {
  "fld1BzaGqBJsUuDp8" : "Resource ID",
  "fldW77CUwEUTcuvbd" : "Content title",
  "fldmbpTGMSFHL6npp" : "Link to content",
  "fldO7IMzt6xr4BrnT" : "Link to description",
  "fldZLktMm2kmHlCKo" : `"About" text`,
  "flddFXSZMW4vMxVlc" : "Link to transcript",
  "fldoQa0DJ3M7UT2Tq" : "Journalist(s) or SME",
  "fldzuWm0K6CoDmJQa" : "Journalist or SME organization(s)",
  "fldaLSqmvLVWkOUab" : "Resource type (USE THIS)",
  "fld3rpFASwoHer6rW" : "Resource type (recent old)",
  "fld39hMYTy3H5wwbv" : "Only on Checkology",
  "fldIlTF1pSIUmlOsA" : "Featured in the Sift",
  "fldz11nODqR9vqIBZ" : "Format(s)",
  "fldtWsb6GDZw8vO0w" : "Grade level/band",
  "fldRUtiJ2H0nx0p2V" : "Classroom needs",
  "fld0Za1UgjTYUX5Pz" : "Subject areas",
  "fldJTqRVs3ndCA4s9" : "NLP standards",
  "fldlTfF974aDo41X5" : "News literacy topics",
  "fldal8WTFwScHioGq" : "Content warnings",
  "fldnrmB5SdKnyD0vc" : "Content warning to be added to content",
  "fldZlkPlwxMqGkauJ" : "Estimated time to complete",
  "fldzqypnyqK9wR7R5" : "Evaluation preference",
  "fldYT9I89ks5SsxBm" : "Assessment types",
  "fldM4FrthY50uOSS0" : "Prerequisites/related",
  "fldbn0QV1bWB9v5X2" : "Creation date",
  "fldVnhITNy2JCMsCh" : "Date of last review",
  "fldBtTBSYdS5cbevA" : "Date of last modification",
  "fldZGu1JF3BGC5CIh" : "Word wall terms",
  "fld0gPF3FjsJBqSlH" : "Word wall terms to link",
  "fld5ccHSabiJVvY1S" : "Media outlets featured",
  "fldASmYbtjuI8PLkT" : "Media outlets mentioned",
  "fldHbBoqsUQfHZDhh" : "Checkology overview page complete",
  "fld1xDg6tpKxJ8YSu" : "Learning objectives and essential questions",
  "fldlHslohZmzqunfb" : "Audit status",
  "fldikjrucd7JFavIL" : "Link to audit",
  "fldAnZsBuzhr2LwdN" : "Status",
  "fldLXPhCas9v1envD" : "Image status",
  "fldGAMv2z4MzNep5s" : "Image group",
  "fldXapcEbq1okHOe1" : "About text characters",
  "fldZEXkkarNPpcFK7" : "Resource type (OLD)",
  "fld8a94N2nGMod371" : "Links to standards alignments",
  "fldriPHo0hKPU6k3a" : "Average completion times",
  "fldbJ3BNqqliMo00K" : "Searchable tags",
  "fldWbZgZpQ2VZx3Es" : "User feedback",
  "fldNaP0AJQ1zkQ1lu" : "Reporters and SMEs",
  "fldvHv2X3hOQkaNDS" : "NLNO top navigation",
  "fld6WP4D46J23PS4s" : "Why should it go dormant?",
  "fldKgw3DohmUpWJ4k" : "Checkology points",
  "fldAY5QOoFJHKvS7o" : "Name of link",
  "fld0Z9MHvOSRRDcmw" : "Link to content (2)",
  "fldsrpjU4mj1Y6rhg" : "Name of link (2)",
  "fldMH3sZQTKWRtUEh" : "Standards alignments",
  "fld0dpSHw5pKvR7jO" : "Primary image",
  "fld7l3N61dl5Uyhi9" : "Primary image alt text",
  "fldfXzZUBGuHlkVri" : "Thumbnail image",
  "fldlViN0lNgSGQLtH" : "Thumbnail image alt text",
  "fldapgECcBSeJp6nr" : "Social image",
  "fldh5lhiiggmU6alh" : "Social image alt text",
  "fldoJCUx9TORSs4HH" : "NewsLitNation exclusive",
  "fld3P8VVMyzOzICxf" : "Design Notes",
  "fldHQaDHHL1kvwgVb" : "NEW: Primary image S3 link",

  ///Below is the arslan airtable field description
  // "fldc2H1I2fR2epttQ": "Content title",
  // "fldp5HrDW01BJvIys": "Status",
  // "fldFh8TdnGfxJYq7Z": "NewsLitNation exclusive",
  // "fldydymQmqfb7HdVi": "Image group",
  // "fldjWTjQgE1761RZ4": "Image status",
  // "fld7Asnj9gVvJow3p": "About text",
  // "fldzH355wem3gvLtH": "Link to transcript",
  // "fldhvzjKHo8HNOWle": "Journalist(s) or SME",
  // "fld7JSomwUvdSNQhG": "Journalist or SME organization(s)",
  // "fldY46Ow5uDW3Pps8": "Resource type (USE THIS)",
  // "fldgDOz9KEdlhx2zD": "Resource type (recent old)",
  // "fldYr4Jy33afhKTDQ": "Resource type (OLD)",
  // "fldEfvrENfLm25S0v": "Only on Checkology",
  // "fldRY8vl0qJoHxdzf": "Featured in the Sift",
  // "fld6E6qo7GZdfUivK": "Format(s)",
  // "fldnjUbISnGXnW7bH": "Name of link",
  // "fldiHSGvuHL7T4cyo": "Link to content",
  // "fldbazwMCSp4Wkzck": "Link to description",
  // "fldLj4JKv0Y4ZHQCc": "Grade level/band",
  // "fldan0DTGvDYxqyn0": "Classroom needs",
  // "fldVkNrDx2oFY3yHE": "Subject areas",
  // "flduUiETVRowzuXRC": "NLP standards",
  // "fldfib7Z6AbYPzZVm": "News literacy topics",
  // "fldqMpIWZbKPt1r5K": "Content warnings",
  // "fldSW0vx4jJPIQ9TZ": "Content warning to be added to content",
  // "fld1kWksYAS780cmS": "Estimated time to complete",
  // "fldiinCAfSTM2EQfI": "Links to standards alignments",
  // "fldV4U0mo8X7K5Qb1": "Average completion times",
  // "fldRW7FZAis07owoy": "Evaluation preference",
  // "fldYjp4TJfsvWdwQT": "Assessment types",
  // "fld1xTnOCK96cAyuQ": "Prerequisites/related",
  // "fldB5xCe1m0ZStAYn": "Searchable tags",
  // "fldpL1SOMG4aqRCgr": "Creation date",
  // "fldXOdq6SxGFKNhvc": "Date of last review",
  // "fldaVyIQftpTd1ETG": "Date of last modification",
  // "fldEf0ryFsxsorsyS": "User feedback",
  // "fldej912m9dZXWSbB": "Word wall terms",
  // "fldP7FENBIw8q9hf1": "Word wall terms to link",
  // "fldlC8TG35oDjOUBy": "Media outlets featured",
  // "fld6JGcTaV6KjGpfg": "Media outlets mentioned",
  // "fldk0Tb1w11BB8tb0": "Reporters and SMEs",
  // "fldHmH0rrzjY5uav6": "Checkology overview page complete",
  // "fld575A27H43puioA": "Learning objectives and essential questions",
  // "fldbHra8LvCUeQ1sP": "NLNO top navigation",
  // "fld9Hq3R7oEhGYcUq": "Field 35",
  // "fldXlZOOdeZ9ohFAQ": "Why should it go dormant?",
  // "fldRK2Cx0E46QP6Is": "Audit status",
  // "fldhk2jBCzoCLjlvw": "Link to audit",
  // "fldpD1WvPFLHVxRs7": "Checkology points",
  // "fld2csHQtBnP780PP": "Link to content (2)",
  // "fldcifY3oCktcHJad": "Name of link (2)",
  // "fldYEUuvtphVjOFtV": "Field 49",
  // "fld6Up2yd0WeFmlWe": "Standards alignments",
  // "fldoTXibWopCbnFUH": "Primary image",
  // "fldWYIQrR6BfbpC0Q": "Primary image alt text",
  // "fldNpqcOpFFNX84tP": "Thumbnail image",
  // "fldfg84Mj6LWErhUv": "Thumbnail image alt text",
  // "fldPDx81qA8pVPiim": "Social image",
  // "fldrRMJKampqxr02L": "Social image alt text"
};
